// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaqVwBptgfkaWRROXzEusWEA0jWlWtCJc',
    appId: '1:307639679594:web:c1ab2637360e4403f0e813',
    messagingSenderId: '307639679594',
    projectId: 'regestration-backend',
    authDomain: 'regestration-backend.firebaseapp.com',
    storageBucket: 'regestration-backend.firebasestorage.app',
    measurementId: 'G-EH87XXLBV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7SgIJhL1GZpSH6VwwJF1i_vzqeAfmG7s',
    appId: '1:307639679594:android:f65f0dfca3583d12f0e813',
    messagingSenderId: '307639679594',
    projectId: 'regestration-backend',
    storageBucket: 'regestration-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYeTJRdn5ta_4MTqn3tHVNxft8aPhxp3U',
    appId: '1:307639679594:ios:84dac44af416d321f0e813',
    messagingSenderId: '307639679594',
    projectId: 'regestration-backend',
    storageBucket: 'regestration-backend.firebasestorage.app',
    iosBundleId: 'com.example.regestrationAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYeTJRdn5ta_4MTqn3tHVNxft8aPhxp3U',
    appId: '1:307639679594:ios:84dac44af416d321f0e813',
    messagingSenderId: '307639679594',
    projectId: 'regestration-backend',
    storageBucket: 'regestration-backend.firebasestorage.app',
    iosBundleId: 'com.example.regestrationAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaqVwBptgfkaWRROXzEusWEA0jWlWtCJc',
    appId: '1:307639679594:web:ff144f9c5914e6a1f0e813',
    messagingSenderId: '307639679594',
    projectId: 'regestration-backend',
    authDomain: 'regestration-backend.firebaseapp.com',
    storageBucket: 'regestration-backend.firebasestorage.app',
    measurementId: 'G-GW8WPQQ5L9',
  );
}
